# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
def even_fibonacci_number(number)
	n0 = 1
	n1 = 2
	sum = 0

	while n0 < number
		n = n0 + n1
		n0 = n1
		n1 = n
		puts "Sequence is #{n0}"
		if n0 % 2 == 0
			puts "++++++++++The number is #{n0}"
			sum = sum + n0
			puts "----------Total sum of #{sum}"
		end
	end
	return sum
end

#even_fibonacci_number(4000000)

